CREATE TABLE MEMBER_LOGIN
(
  CUSTOMER_NO     INT         NOT NULL,
  PASSWORD        VARCHAR(60) NOT NULL,
  LAST_PASSWORD   VARCHAR(60),
  LOGIN_DATE_TIME TIMESTAMP,
  LOGIN_FLG       BOOLEAN     NOT NULL
);

ALTER TABLE MEMBER_LOGIN
  ADD CONSTRAINT PK_MEMBER_LOGIN PRIMARY KEY (CUSTOMER_NO);

CREATE TABLE MEMBER
(
  CUSTOMER_NO       INT          NOT NULL AUTO_INCREMENT PRIMARY KEY,
  KANJI_FAMILY_NAME VARCHAR(10)  NOT NULL,
  KANJI_GIVEN_NAME  VARCHAR(10)  NOT NULL,
  KANA_FAMILY_NAME  VARCHAR(10)  NOT NULL,
  KANA_GIVEN_NAME   VARCHAR(10)  NOT NULL,
  BIRTHDAY          DATE         NOT NULL,
  GENDER            VARCHAR(1)   NOT NULL,
  TEL               VARCHAR(13)  NOT NULL,
  ZIP_CODE          VARCHAR(7)   NOT NULL,
  ADDRESS           VARCHAR(60)  NOT NULL,
  MAIL              VARCHAR(256) NOT NULL,
  CREDIT_NO         VARCHAR(16)  NOT NULL,
  CREDIT_TYPE_CD    VARCHAR(3)   NOT NULL,
  CREDIT_TERM       VARCHAR(5)   NOT NULL
);

CREATE TABLE CREDIT_TYPE
(
  CREDIT_TYPE_CD VARCHAR(3)  NOT NULL,
  CREDIT_FIRM    VARCHAR(80) NOT NULL,
  DISPLAY_ORDER  INT         NOT NULL UNIQUE
);

ALTER TABLE CREDIT_TYPE
  ADD CONSTRAINT PK_CREDIT_TYPE PRIMARY KEY (CREDIT_TYPE_CD);


ALTER TABLE MEMBER_LOGIN
  ADD CONSTRAINT FK_MEMBER_LOGIN_1 FOREIGN KEY (CUSTOMER_NO) REFERENCES MEMBER (CUSTOMER_NO);


ALTER TABLE MEMBER
  ADD CONSTRAINT FK_MEMBER_1 FOREIGN KEY (CREDIT_TYPE_CD) REFERENCES CREDIT_TYPE (CREDIT_TYPE_CD);