INSERT INTO CREDIT_TYPE (CREDIT_TYPE_CD, CREDIT_FIRM, DISPLAY_ORDER) VALUES ('VIS', 'VISA', 1);
INSERT INTO CREDIT_TYPE (CREDIT_TYPE_CD, CREDIT_FIRM, DISPLAY_ORDER) VALUES ('MTR', 'MASTER', 2);
INSERT INTO CREDIT_TYPE (CREDIT_TYPE_CD, CREDIT_FIRM, DISPLAY_ORDER) VALUES ('JCB', 'JCB', 3);
INSERT INTO CREDIT_TYPE (CREDIT_TYPE_CD, CREDIT_FIRM, DISPLAY_ORDER) VALUES ('DNS', 'DNS', 4);
INSERT INTO CREDIT_TYPE (CREDIT_TYPE_CD, CREDIT_FIRM, DISPLAY_ORDER) VALUES ('AMX', 'American Express', 5);